### ISSUE TITLE
The library.properties file date was not updated when the library was updated.

### ISSUE THREAD

**Issue by mrtktabornsr** [arduino-libraries/Arduino_DebugUtils#23]
The library.properties file is out of date. It was updated Aug 25, 2020. The library was updated Feb 18, 2022 to add add "newlineOn" and "newlineOff" methods. I believe this is preventing the Arduino library manager from updating.

**Comment by per1234** [comment]
Hi @mrtktabornsr. Thanks for your report.

>I believe this is preventing the Arduino library manager from updating.

That is incorrect. The Arduino Library Manager works from Git tags. The latest Git tag is version 1.1.0, which is available for installation via Library Manager:

![image](https://user-images.githubusercontent.com/8572152/173662215-aa216e51-8322-417c-aa3b-3253cf94acb7.png)

It is normal and expected that any changes made after the time of the latest Git tag will not be available from the Library Manager installation of the library:

https://github.com/arduino-libraries/Arduino_DebugUtils/compare/1.1.0...master

If you need those changes, you can do a [manual installation](https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries#manual-installation) of the beta tester version of the library downloaded via the <kbd>**Code ▾**<kbd> button here:

https://github.com/arduino-libraries/Arduino_DebugUtils

(Make sure to replace the Library Manager version if you do that so that the manually installed version will be used by the Arduino IDE).

**Comment by aentinger** [comment]
Hi @mrtktabornsr :coffee: :wave:

I took this opportunity to create a new library release. You can now install [v1.2.0](https://github.com/arduino-libraries/Arduino_DebugUtils/releases/tag/1.2.0) via library manager too.
